### ISSUE TITLE
Need LVGL as dependency

### ISSUE THREAD

**Issue by zhengruiw02** [iDalink/lv_terminal#1]
I've pulled this repo and try to build according to README.zh-CN.md and found at final step on build image it failed with following message. Then I realize that this project need LVGL support, which esp-idf doesn't contains it. Please help to double check it, thanks.

```
main/ic_back.c:4:10: fatal error: lvgl/lvgl.h: No such file or directory
    4 | #include "lvgl/lvgl.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by iDalink** [comment]
lvgl是esp-box项目提供的，位于components/lvgl目录下。https://gitee.com/EspressifSystems/esp-box.git
